s=int(input())
height=int(input())
base=int(input())
length=int(input())
breadth=int(input())
print("Area of traingle :",((1/2)*height*base))
print("Area of rectangle:",length*breadth)
print("Area of square:",s*s)